# -*- coding: utf-8 -*-
"""DDRNet_HBD_B2N_DGT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vOO_VLj75PrSNDIQIhg7lzmk0xMdl4jw

#DDRNet+hardnet+bottle2nek+DetailGT

Output:
1. `seghead(FFM(DAPPPM, layer5_)` - main
2. `seghead(layer3_ + upsample(layer3))`
3. `seghead(layer4_ + upsample(layer4))`
"""

import sys
sys.path.insert(0, '.')
import os
import logging
import random
import time
import math
import torch
import numpy as np 
import torch.nn as nn
import torch.nn.functional as F

from torch.nn import init
from torch.utils import data
from datetime import datetime, timedelta


BatchNorm2d = nn.BatchNorm2d
ReLU = nn.ReLU
AvgPool2d = nn.AvgPool2d
AdaptiveAvgPool2d = nn.AdaptiveAvgPool2d

os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

batch_size = 8
n_workers = 2
print_interval=10
val_interval=500

n_classes = 19

model_arch = 'ddrnet_slim_23'

bn_mom = 0.1

# Setup device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
float_tensor_type = torch.cuda.FloatTensor if device.type=='cuda' else torch.FloatTensor

"""---
## Network
"""

class ConvBNReLU(nn.Module):
    def __init__(self, in_chan, out_chan, ks=3, stride=1, padding=1, need_relu=True, *args, **kwargs):
        super(ConvBNReLU, self).__init__()
        self.conv = nn.Conv2d(in_chan,
                out_chan,
                kernel_size = ks,
                stride = stride,
                padding = padding,
                bias = False)
        # self.bn = BatchNorm2d(out_chan)
        self.bn = BatchNorm2d(out_chan)
        self.need_relu = need_relu
        if need_relu:
            self.relu = nn.ReLU(inplace=True)
        self.init_weight()

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        if self.need_relu:
            x = self.relu(x)
        return x

    def init_weight(self):
        for ly in self.children():
            if isinstance(ly, nn.Conv2d):
                nn.init.kaiming_normal_(ly.weight, a=1)
                if not ly.bias is None: nn.init.constant_(ly.bias, 0)

    def get_params(self):
        wd_params, nowd_params = [], []
        for name, module in self.named_modules():
            if isinstance(module, nn.Conv2d):
                wd_params.append(module.weight)
                if not module.bias is None:
                    nowd_params.append(module.bias)
            elif isinstance(module, (BatchNorm2d, ReLU)):
                nowd_params += list(module.parameters())
        return wd_params, nowd_params

class StepDAPPM(nn.Module):
    def __init__(self, pool_ks, pool_stride, pool_padding, bn_inplanes, conv_out_planes, conv_ks=1):
        super(StepDAPPM, self).__init__()
        self.pool = None
        if pool_ks > 1:
            self.pool = nn.AvgPool2d(kernel_size=pool_ks, stride=pool_stride, padding=pool_padding)
        elif pool_ks == 1:
            self.pool = nn.AdaptiveAvgPool2d((1, 1))

        self.bn = BatchNorm2d(bn_inplanes, momentum=bn_mom)
        self.relu = nn.ReLU(inplace=True)
        self.conv = nn.Conv2d(bn_inplanes, conv_out_planes, kernel_size=conv_ks, padding=conv_ks//2, bias=False)

    def forward(self, x):
        if self.pool is not None:
            x = self.pool(x)
        x = self.conv(self.relu(self.bn(x)))
        return x
    
    def get_params(self):
        wd_params, nowd_params = [], []
        for name, module in self.named_modules():
            if isinstance(module, nn.Conv2d):
                wd_params.append(module.weight)
                if not module.bias is None:
                    nowd_params.append(module.bias)
            elif isinstance(module, (BatchNorm2d, ReLU)):
                nowd_params += list(module.parameters())
        return wd_params, nowd_params

class DAPPM(nn.Module):
    def __init__(self, inplanes, branch_planes, outplanes):
        super(DAPPM, self).__init__()
        self.scale1 = StepDAPPM( 5, 2, 2, inplanes, branch_planes, conv_ks=1)
        self.scale2 = StepDAPPM( 9, 4, 4, inplanes, branch_planes, conv_ks=1)
        self.scale3 = StepDAPPM(17, 8, 8, inplanes, branch_planes, conv_ks=1)
        self.scale4 = StepDAPPM( 1, 0, 0, inplanes, branch_planes, conv_ks=1)
        self.scale0 = StepDAPPM( 0, 0, 0, inplanes, branch_planes, conv_ks=1)

        self.process1 = StepDAPPM(0, 0, 0, branch_planes, branch_planes, conv_ks=3)
        self.process2 = StepDAPPM(0, 0, 0, branch_planes, branch_planes, conv_ks=3)
        self.process3 = StepDAPPM(0, 0, 0, branch_planes, branch_planes, conv_ks=3)
        self.process4 = StepDAPPM(0, 0, 0, branch_planes, branch_planes, conv_ks=3)
        
        self.compression = StepDAPPM(0, 0, 0, branch_planes * 5, outplanes, conv_ks=1)
        self.shortcut = StepDAPPM(0, 0, 0, inplanes, outplanes, conv_ks=1)
        
    def forward(self, x):

        #x = self.downsample(x)
        width = x.shape[-1]
        height = x.shape[-2]
        x_list = []

        x_list.append(self.scale0(x))
        x_list.append(self.process1((F.interpolate(self.scale1(x),
                        size=[height, width],
                        mode='bilinear', align_corners=True)+x_list[0])))
        x_list.append((self.process2((F.interpolate(self.scale2(x),
                        size=[height, width],
                        mode='bilinear', align_corners=True)+x_list[1]))))
        x_list.append(self.process3((F.interpolate(self.scale3(x),
                        size=[height, width],
                        mode='bilinear', align_corners=True)+x_list[2])))
        x_list.append(self.process4((F.interpolate(self.scale4(x),
                        size=[height, width],
                        mode='bilinear', align_corners=True)+x_list[3])))
       
        out = self.compression(torch.cat(x_list, 1)) + self.shortcut(x)
        return out    

    def get_params(self):
        wd_params, nowd_params = [], []
        for name, child in self.named_children():
            child_wd_params, child_nowd_params = child.get_params() \
                if not isinstance(child, ReLU) else ([],[])
            wd_params += child_wd_params
            nowd_params += child_nowd_params
        return wd_params, nowd_params

class segmenthead(nn.Module):

    def __init__(self, inplanes, interplanes, outplanes, scale_factor=None):
        super(segmenthead, self).__init__()
        self.bn1 = BatchNorm2d(inplanes, momentum=bn_mom)
        self.conv1 = nn.Conv2d(inplanes, interplanes, kernel_size=3, padding=1, bias=False)
        self.bn2 = BatchNorm2d(interplanes, momentum=bn_mom)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(interplanes, outplanes, kernel_size=1, padding=0, bias=True)
        self.scale_factor = scale_factor

    def forward(self, x):
        
        x = self.conv1(self.relu(self.bn1(x)))
        out = self.conv2(self.relu(self.bn2(x)))

        if self.scale_factor is not None:
            height = x.shape[-2] * self.scale_factor
            width = x.shape[-1] * self.scale_factor
            out = F.interpolate(out,
                        size=[height, width],
                        mode='bilinear', align_corners=True)

        return out
    
    def get_params(self):
        wd_params, nowd_params = [], []
        for name, module in self.named_modules():
            if isinstance(module, (nn.Conv2d)):
                wd_params.append(module.weight)
                if not module.bias is None:
                    nowd_params.append(module.bias)
            elif isinstance(module, (BatchNorm2d, ReLU)):
                nowd_params += list(module.parameters())
        return wd_params, nowd_params

class FeatureFusionModule(nn.Module):
    def __init__(self, in_chan, out_chan, *args, **kwargs):
        super(FeatureFusionModule, self).__init__()
        self.convblk = ConvBNReLU(in_chan, out_chan, ks=1, stride=1, padding=0)
        self.conv1 = nn.Conv2d(out_chan,
                out_chan//4,
                kernel_size = 1,
                stride = 1,
                padding = 0,
                bias = False)
        self.conv2 = nn.Conv2d(out_chan//4,
                out_chan,
                kernel_size = 1,
                stride = 1,
                padding = 0,
                bias = False)
        self.relu = nn.ReLU(inplace=True)
        self.sigmoid = nn.Sigmoid()
        self.init_weight()

    def forward(self, fsp, fcp):
        fcat = torch.cat([fsp, fcp], dim=1)
        feat = self.convblk(fcat)
        atten = F.avg_pool2d(feat, feat.size()[2:])
        atten = self.conv1(atten)
        atten = self.relu(atten)
        atten = self.conv2(atten)
        atten = self.sigmoid(atten)
        feat_atten = torch.mul(feat, atten)
        feat_out = feat_atten + feat
        return feat_out

    def init_weight(self):
        for ly in self.children():
            if isinstance(ly, nn.Conv2d):
                nn.init.kaiming_normal_(ly.weight, a=1)
                if not ly.bias is None: nn.init.constant_(ly.bias, 0)

    def get_params(self):
        wd_params, nowd_params = [], []
        for name, module in self.named_modules():
            if isinstance(module, (nn.Linear, nn.Conv2d)):
                wd_params.append(module.weight)
                if not module.bias is None:
                    nowd_params.append(module.bias)
            elif isinstance(module, (BatchNorm2d, ReLU)):
                nowd_params += list(module.parameters())
        return wd_params, nowd_params

class HarDBlock(nn.Module):
    def __init__(self, in_channels, growth_rate, grmul, n_layers, keepBase=False):
        super(HarDBlock, self).__init__()
        self.in_channels = in_channels
        self.growth_rate = growth_rate
        self.grmul = grmul
        self.links = []
        self.out_channels = 0
        self.keepBase = keepBase
        self.layers = nn.ModuleList([])
        for i in range(n_layers):
            out_ch, in_ch, el_links = self.get_links(i+1)
            self.links.append(el_links)
            self.layers.append(ConvBNReLU(in_ch, out_ch, need_relu=(n_layers - 1 != i)))
            if (i % 2 == 0) or (i == n_layers - 1):
                self.out_channels += out_ch

    def __out_ch(self, layer_id): 
        out_ch = self.growth_rate
        for i in range(1, int(math.log2(layer_id))+1):
            if layer_id % 2**i == 0:
                out_ch = out_ch*self.grmul
        return int(int(out_ch + 1) / 2) * 2

    def get_links(self, layer_id):
        in_ch = 0
        links_ = []
        for i in range(int(math.log2(layer_id))):
            diff = 2**i
            if (layer_id % diff == 0) and layer_id - diff > 0:
                in_ch += self.__out_ch(layer_id - diff)
                links_.append(layer_id - diff)
        if math.log2(layer_id).is_integer():
            in_ch += self.in_channels
            links_.append(0)
        return self.__out_ch(layer_id), in_ch, links_

    def forward(self, x):
        data = [x]
        for layer in range(len(self.layers)):
            layer_input = []
            for link in self.links[layer]:
                layer_input.append(data[link])
            in_ = layer_input[0] if len(layer_input) == 1 \
                else torch.cat(layer_input, dim=1)
            data.append(self.layers[layer](in_))
        t = len(data)
        out = []
        for i in range(t):
            if (i % 2 == 1) or (self.keepBase and i == 0) or (i == t-1):
                out.append(data[i])
        return torch.cat(out, dim=1)
    
    def get_out_ch(self):
        return self.out_channels

    def get_params(self):
        wd_params, nowd_params = [], []
        for name, child in self.layers.named_children():
            child_wd_params, child_nowd_params = child.get_params() \
                if not isinstance(child, ReLU) else ([],[])
            wd_params += child_wd_params
            nowd_params += child_nowd_params
        return wd_params, nowd_params

class ConvHarDBlock(nn.Module):
    def __init__(self, inplanes, planes, stride=1, growth_rate=10, grmul=1.7, n_layers=4):
        super(ConvHarDBlock, self).__init__()
        self.layers = nn.ModuleList([])
        if stride != 1:
            self.layers.append(ConvBNReLU(inplanes, planes, ks=1, stride=stride,\
                                          padding=0, need_relu=True))
        hardblock_inplanes = planes if stride != 1 else inplanes
        hardblock = HarDBlock(hardblock_inplanes, growth_rate, grmul, n_layers)
        self.layers.append(hardblock)

        self.layers.append(ConvBNReLU(hardblock.get_out_ch(), planes, ks=1, \
                                      stride=1, padding=0, need_relu=True))
    
    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x        

    def get_params(self):
        wd_params, nowd_params = [], []
        for name, child in self.layers.named_children():
            child_wd_params, child_nowd_params = child.get_params() \
                if not isinstance(child, ReLU) else ([],[])
            wd_params += child_wd_params
            nowd_params += child_nowd_params
        return wd_params, nowd_params

class Bottle2neck(nn.Module):
    expansion = 2

    def __init__(self, inplanes, planes, stride=1, downsample=None, baseWidth=26, scale = 4, stype='normal'):
        """ Constructor
        Args:
            inplanes: input channel dimensionality
            planes: output channel dimensionality
            stride: conv stride. Replaces pooling layer.
            downsample: None when stride = 1
            baseWidth: basic width of conv3x3
            scale: number of scale.
            type: 'normal': normal set. 'stage': first block of a new stage.
        """
        super(Bottle2neck, self).__init__()

        width = int(math.floor(planes * (baseWidth/64.0)))
        self.conv1 = nn.Conv2d(inplanes, width*scale, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(width*scale)
        
        if scale == 1:
          self.nums = 1
        else:
          self.nums = scale -1
        if stype == 'stage':
            self.pool = nn.AvgPool2d(kernel_size=3, stride = stride, padding=1)
        convs = []
        bns = []
        for i in range(self.nums):
          convs.append(nn.Conv2d(width, width, kernel_size=3, stride = stride, padding=1, bias=False))
          bns.append(nn.BatchNorm2d(width))
        self.convs = nn.ModuleList(convs)
        self.bns = nn.ModuleList(bns)

        self.conv3 = nn.Conv2d(width*scale, planes * self.expansion, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * self.expansion)

        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stype = stype
        self.scale = scale
        self.width  = width

    def forward(self, x):
        
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        spx = torch.split(out, self.width, 1)
        for i in range(self.nums):
          if i==0 or self.stype=='stage':
            sp = spx[i]
          else:
            sp = sp + spx[i]
          sp = self.convs[i](sp)
          sp = self.relu(self.bns[i](sp))
          if i==0:
            out = sp
          else:
            out = torch.cat((out, sp), 1)
        if self.scale != 1 and self.stype=='normal':
          out = torch.cat((out, spx[self.nums]),1)
        elif self.scale != 1 and self.stype=='stage':
          out = torch.cat((out, self.pool(spx[self.nums])),1)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out

    def get_params(self):
        wd_params, nowd_params = [], []
        for name, module in self.named_modules():
            if isinstance(module, (nn.Linear, nn.Conv2d)):
                wd_params.append(module.weight)
                if not module.bias is None:
                    nowd_params.append(module.bias)
            elif isinstance(module, (BatchNorm2d, ReLU)):
                nowd_params += list(module.parameters())
        return wd_params, nowd_params

class DualResNet(nn.Module):

    def __init__(self, num_classes=19, planes=64, spp_planes=128, head_planes=128, augment=False):
        super(DualResNet, self).__init__()

        growth_rate = [  10,16,18,24,32]
        highres_planes = planes * 2
        self.augment = augment


        self.conv0 = ConvBNReLU(     3, planes, ks=3, stride=2, padding=1)
        self.conv1 = ConvBNReLU(planes, planes, ks=3, stride=2, padding=1)

        # self.conv1 =  nn.Sequential(
        #                   nn.Conv2d(3,planes,kernel_size=3, stride=2, padding=1),
        #                   BatchNorm2d(planes, momentum=bn_mom),
        #                   nn.ReLU(inplace=True),
        #                   nn.Conv2d(planes,planes,kernel_size=3, stride=2, padding=1),
        #                   BatchNorm2d(planes, momentum=bn_mom),
        #                   nn.ReLU(inplace=True),
        #               )
        
        self.relu = nn.ReLU(inplace=False)
        
        self.layer1 = ConvHarDBlock(planes,     planes,     stride=1, growth_rate=growth_rate[0])
        self.layer2 = ConvHarDBlock(planes,     planes * 2, stride=2, growth_rate=growth_rate[1])
        self.layer3 = ConvHarDBlock(planes * 2, planes * 4, stride=2, growth_rate=growth_rate[2])
        self.layer4 = ConvHarDBlock(planes * 4, planes * 8, stride=2, growth_rate=growth_rate[3])


        self.compression3 = ConvBNReLU(planes * 4, highres_planes, ks=1, stride=1, padding=0, need_relu=False)
        self.compression4 = ConvBNReLU(planes * 8, highres_planes, ks=1, stride=1, padding=0, need_relu=False)

        # self.compression3 = nn.Sequential(
        #                                   nn.Conv2d(planes * 4, highres_planes, kernel_size=1, bias=False),
        #                                   BatchNorm2d(highres_planes, momentum=bn_mom),
        #                                   )

        # self.compression4 = nn.Sequential(
        #                                   nn.Conv2d(planes * 8, highres_planes, kernel_size=1, bias=False),
        #                                   BatchNorm2d(highres_planes, momentum=bn_mom),
        #                                   )


        self.down3 = ConvBNReLU(highres_planes, planes * 4, ks=3, stride=2, padding=1, need_relu=False)
        self.down4_0 = ConvBNReLU(highres_planes, planes * 4, ks=3, stride=2, padding=1, need_relu=True)
        self.down4_1 = ConvBNReLU(planes * 4, planes * 8, ks=3, stride=2, padding=1, need_relu=False)
        # self.down3 = nn.Sequential(
        #                            nn.Conv2d(highres_planes, planes * 4, kernel_size=3, stride=2, padding=1, bias=False),
        #                            BatchNorm2d(planes * 4, momentum=bn_mom),
        #                            )

        # self.down4 = nn.Sequential(
        #                            nn.Conv2d(highres_planes, planes * 4, kernel_size=3, stride=2, padding=1, bias=False),
        #                            BatchNorm2d(planes * 4, momentum=bn_mom),
        #                            nn.ReLU(inplace=True),
        #                            nn.Conv2d(planes * 4, planes * 8, kernel_size=3, stride=2, padding=1, bias=False),
        #                            BatchNorm2d(planes * 8, momentum=bn_mom),
        #                            )

        self.layer3_ = ConvHarDBlock(planes * 2, highres_planes, stride=1, growth_rate=growth_rate[2])
        
        self.layer4_ = ConvHarDBlock(highres_planes, highres_planes, stride=1, growth_rate=growth_rate[2])

        self.layer5_ = self._make_bottle2neck(highres_planes, highres_planes)
        
        self.layer5 =  self._make_bottle2neck(planes * 8, planes * 8, stride=2)
        
        self.spp = DAPPM(planes * 8 * Bottle2neck.expansion, spp_planes, planes * 4)

        self.ffm = FeatureFusionModule(planes * 4 + highres_planes * 2, planes * 4)

        self.seghead_out1 = segmenthead(planes * 4, head_planes, num_classes)
        self.seghead_out2 = segmenthead(highres_planes, head_planes, 1)
        self.seghead_out3 = segmenthead(highres_planes, head_planes, num_classes)            

        self.init_weights()

    def init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def _make_bottle2neck(self, inplanes, planes, stride=1):
        '''
            outplanes = planes * 4
        '''

        downsample = None
        if stride != 1 or inplanes != planes * Bottle2neck.expansion:
            downsample = ConvBNReLU(inplanes, planes * Bottle2neck.expansion, ks=3, stride=stride, need_relu=False)
        stype = 'stage' if stride != 1 else 'normal'
        
        return Bottle2neck(inplanes, planes, stride, downsample, stype=stype)


    def forward(self, x):

        width, height = x.shape[-1], x.shape[-2]
        width_output, height_output = x.shape[-1] // 8, x.shape[-2] // 8

        layers = []

        x = self.conv0(x)
        x = self.conv1(x)

        x = self.layer1(x)
        layers.append(x)

        x = self.layer2(self.relu(x))
        layers.append(x)
  
        x = self.layer3(self.relu(x))
        layers.append(x)
        x_ = self.layer3_(self.relu(layers[1]))

        x = x + self.down3(self.relu(x_))
        step_res = self.compression3(self.relu(layers[2]))
        x_ = x_ + F.interpolate(
                        step_res,
                        size=[height_output, width_output],
                        mode='bilinear', align_corners=True)
        out_2 = x_

        x = self.layer4(self.relu(x))
        layers.append(x)
        x_ = self.layer4_(self.relu(x_))

        x = x + self.down4_1(self.down4_0(self.relu(x_)))
        x_ = x_ + F.interpolate(
                        self.compression4(self.relu(layers[3])),
                        size=[height_output, width_output],
                        mode='bilinear', align_corners=True)
        
        out_3 = x_

        x_ = self.layer5_(self.relu(x_))
        x = F.interpolate(
                        self.spp(self.layer5(self.relu(x))),
                        size=[height_output, width_output],
                        mode='bilinear', align_corners=True)
        
        out_1 = self.ffm(x, x_)
        
        out_1 = self.seghead_out1(out_1)
        out_2 = self.seghead_out2(out_2)
        out_3 = self.seghead_out3(out_3)

        out_1 = F.interpolate(out_1, (height, width), mode='bilinear', align_corners=True)
        out_2 = F.interpolate(out_2, (height, width), mode='bilinear', align_corners=True)
        out_3 = F.interpolate(out_3, (height, width), mode='bilinear', align_corners=True)
        
        return out_1, out_2, out_3
        # return x


    def get_params(self):
        wd_params, nowd_params = [], []
        for name, child in self.named_children():
            child_wd_params, child_nowd_params = child.get_params() \
                if not isinstance(child, ReLU) else ([],[])
            wd_params += child_wd_params
            nowd_params += child_nowd_params
        return wd_params, nowd_params


def DualResNet_imagenet(augument=False):
    model = DualResNet(num_classes=19, planes=64, spp_planes=128, head_planes=128, augment=augument)
    return model

def get_seg_model(augument=False):
    model = DualResNet_imagenet(augument=augument)
    return model